store/orders/urls.py
from django.urls import path, include

from orders.views import OrderCreateView, Success

app_name = 'orders'

urlpatterns = [
   path('order-create/', OrderCreateView.as_view(), name='order-create'),
   path('success/', Success.as_view(), name='success'),
   # path('order-create/', order, name='order-create')
]

store/products/urls.py
from django.urls import path, include

from products.views import products, basket_add, about, product_page
app_name = 'products'

urlpatterns = [
  path('', products, name='index'),
  path('category/<int:category_id>/', products, name='category'),
  path('page/<int:page_number>/', products, name='paginator'),
  path('filter/<int:filter_id>', products, name='filter'),
  path('baskets/add/<int:product_id>/', basket_add, name='basket_add'),
  path('about/', about, name='about'),
  path('product_page/<int:product_id>/', product_page, name='product_page'),
  # path('quantity_input/<int:product_id>/', quantity_input, name='quantity_input'),
]

store/store/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from products.views import index
# from store.admin import admin_site
from django.contrib import admin

admin.site.site_header = 'Панель администрации'  # default: "Django Administration"
admin.site.index_title = 'Админ панель'
admin.site.site_title = 'Пользователь'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('products/', include('products.urls', namespace='products')),
    path('users/', include('users.urls', namespace='users')),
    path('account/', include("django.contrib.auth.urls")),
    path('orders/', include('orders.urls', namespace='orders')),
    path('accounts/', include('allauth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/users/urls.py
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from users.views import login, registration, logout, WebPasswordResetView, profile
from orders.views import OrderListView

app_name = 'users'

urlpatterns = [
  path('login/', login, name='login'),
  path('registration/', registration, name='registration'),
  path('profile/', profile, name='profile'),
  path('logout/', logout, name='logout'),
  path("password_reset/", WebPasswordResetView.as_view(), name="password_reset"),
  # path("password_reset/success/", WebPasswordResetDone.as_view(), name="password_reset_success"),
  path('profile/', OrderListView.as_view(), name="orders_list"),

]

store/products/models.py
from django.db import models

from users.models import User


class ProductCategory(models.Model):
    name = models.CharField(max_length=128, unique=True)
    description = models.TextField(null=True, blank=True)

    def __str__(self):
        return self.name


class ProductFilter(models.Model):
    name = models.CharField(max_length=128, unique=True)

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=256)
    description = models.TextField()
    price = models.DecimalField(max_digits=6, decimal_places=2)
    quantity = models.PositiveIntegerField(default=0)
    image = models.ImageField(upload_to='product_images')
    category = models.ForeignKey(to=ProductCategory, on_delete=models.CASCADE)

    def __str__(self):
        return f'Продукт: {self.name} | Категория: {self.category.name} '


class BasketQuerySet(models.QuerySet):
    def total_sum(self):
        return sum(basket.sum() for basket in self)

    def total_quantity(self):
        return sum(basket.quantity for basket in self)


class Basket(models.Model):
    user = models.ForeignKey(to=User, on_delete=models.CASCADE)
    product = models.ForeignKey(to=Product, on_delete=models.CASCADE)
    quantity = models.PositiveSmallIntegerField(default=0)
    created_timestamp = models.DateTimeField(auto_now_add=True)

    objects = BasketQuerySet.as_manager()

    def __str__(self):
        return f'Корзина для {self.user.username} | Продукт: {self.product.name}'

    def sum(self):
        return self.product.price * self.quantity

store/products/forms.py
from django import forms

from products.models import Product, Basket


class QuantityForm(forms.ModelForm):
    quantity = forms.IntegerField(widget=forms.NumberInput(attrs={
        'class': 'block_quantity__number', 'placeholder': '1', 'min': 1,
    }))

    class Meta:
        model = Basket
        fields = ('quantity',)

store/products/views.py
from django.shortcuts import render, HttpResponseRedirect, redirect
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from products.models import ProductCategory, Product, Basket, ProductFilter
from products.forms import QuantityForm
from users.models import User
from products.models import Product
from django.core.paginator import Paginator


def index(request):
    context = {'title': 'Салон проката', }
    return render(request, 'products/index.html', context)


def products(request, category_id=None, filter_id=None, page_number=1):
    if category_id:
        category = ProductCategory.objects.get(id=category_id)
        products = Product.objects.filter(category=category)

    elif filter_id:
        if filter_id == 1:
            products = Product.objects.all().order_by('price')
        elif filter_id == 2:
            products = Product.objects.all().order_by('-price')
        elif filter_id == 3:
            products = Product.objects.all().order_by('name')
        elif filter_id == 4:
            products = Product.objects.filter(price__lt=600)

    else:
        products = Product.objects.all()

    per_page = 3
    paginator = Paginator(products, per_page)
    products_paginator = paginator.page(page_number)

    context = {
        'title': 'Прокат - Каталог',
        'categories': ProductCategory.objects.all(),
        'products': products_paginator,
        'filters': ProductFilter.objects.all(),
    }
    return render(request, 'products/products.html', context)


@login_required
def basket_add(request, product_id):
    product = Product.objects.get(id=product_id)
    baskets = Basket.objects.filter(user=request.user, product=product)

    if not baskets.exists():
        Basket.objects.create(user=request.user, product=product, quantity=1)
    else:
        basket = baskets.first()
        # basket.quantity += 1
        basket.save()

        return redirect('orders:order-create')

        # return HttpResponseRedirect(request.META['HTTP_REFERER'])
        # return render(request, 'orders/order-create.html')


def product_page(request, product_id):
    product = Product.objects.get(id=product_id)
    dele = Basket.objects.get(user=request.user)
    dele.delete()
    basket, created = Basket.objects.get_or_create(user=request.user, product=product)
    if request.method == 'POST':
        form = QuantityForm(instance=basket, data=request.POST)
        if form.is_valid():
            form.save()
            # return HttpResponseRedirect(reverse('products:product_page'))
    else:
        form = QuantityForm()
    return render(request, 'products/product_page.html', {'product': product, 'form': form})


# def quantity_input(request, product_id):
#     product = Product.objects.get(id=product_id)
#     basket = Basket.objects.get(user=request.user, product=product)
#     if request.method == 'POST':
#         form = QuantityForm(instance=basket, data=request.POST)
#         if form.is_valid():
#             form.save()
#
#     else:
#         form = QuantityForm(instance=basket)
#     context = {'form': form}
#     return render(request, context)


def about(request):
    return render(request, 'products/about.html')

store/products/templates/products/base.html
{% load static %}


<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title> Салон проката </title>


     <link rel="shortcut icon" type="image/png" href="{% static "vendor/icon/darkicon.png" %}">
    <!-- Bootstrap core CSS -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">


    <link rel="stylesheet" href="{% static 'vendor/css/products.css' %}" id="theme" >

    <!-- Custom styles for this template -->
    {% block css %} {% endblock %}

</head>

<body>

<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top my-navbar">
    <div class="container">
        <a class="navbar-brand" href="{% url 'index' %}">Store</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <li class="nav-link"><button id= "switchMode">Switch</button></li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'products:index' %}">Каталог <i class="fas fa-shopping-bag"></i>
                    </a>
                </li>
                {% if user.is_authenticated %}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                           data-bs-toggle="dropdown" aria-expanded="false">
                            <i class="fas fa-user-circle"></i>
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li>
                                <a class="dropdown-item" href="#">Профиль</a>
                            </li>
                            {% if user.is_superuser or user.is_staff %}
                                <li>
                                    <a class="dropdown-item" href="{% url 'admin:index' %}">
                                        Админ-панель
                                    </a>
                                </li>
                            {% endif %}
                            <li>
                                <hr class="dropdown-divider">
                            </li>
                            <li>
                                <a class="dropdown-item" href="{% url 'users:logout' %}">
                                    Выйти
                                </a>
                            </li>
                        </ul>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:login' %}">Войти <i class="fas fa-sign-in-alt"></i></a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

{% block content %} {% endblock %}

{% block footer %} {% endblock %}

<script>
    document.addEventListener('DOMContentLoaded', function () {
        // Получаем элементы
        let switchMode = document.getElementById("switchMode");
        let theme = document.getElementById("theme");

        // Проверка сохраненной темы в локальном хранилище
        const savedTheme = localStorage.getItem('theme');
        if (savedTheme) {
            theme.href = savedTheme;
        }

        // Обработчик события для переключения темы
        switchMode.onclick = function () {
            // Переключение между темами
            if (theme.getAttribute("href") === "{% static 'vendor/css/products.css' %}") {
                theme.href = "{% static 'vendor/css/dark-mode.css' %}";
            } else {
                theme.href = "{% static 'vendor/css/products.css' %}";
            }

            // Сохранение выбранной темы в локальном хранилище
            localStorage.setItem('theme', theme.href);
        };
    });
</script>


<!-- Bootstrap core JavaScript -->
<script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>

<!-- FontAwesome script -->
<script src="{% static 'vendor/fontawesome/fontawesome-icons.js' %}" crossorigin="anonymous"></script>

</body>

</html>

store/products/templates/products/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{{title}}</title>


{#    <link href="{% static "vendor/icon/favicon.ico" %}" type="image/x-icon">#}
{#    <link href="{% static "vendor/icon/favicon.ico" %}" type="image/x-icon">#}


    <link rel="shortcut icon" type="image/png" href="{% static "vendor/icon/darkicon.png" %}">

    <!-- Bootstrap core CSS -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{%  static 'vendor/css/index.css' %}" rel="stylesheet">
    <link href="{%  static 'vendor/css/menu.css' %}" rel="stylesheet">

</head>

<body>

<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
        <a class="navbar-brand" href="{% url 'index' %}">Прокат</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'products:index' %}">Каталог <i class="fas fa-shopping-bag"></i> </a>
                </li>
{% if user.is_authenticated %}
                <li class="nav-item dropdown">
                     <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                       data-bs-toggle="dropdown" aria-expanded="false">
                        <i class="fas fa-user-circle"></i>
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <li>
                            <a class="dropdown-item" href="{% url 'users:profile' %}">Профиль</a>
                        </li>
                        {% if user.is_superuser or user.is_staff %}
                        	<li><a class="dropdown-item" href="{% url 'admin:index' %}">Админ-панель</a></li>
                        {% endif %}
                               <li>
                            <hr class="dropdown-divider">
                        </li>
                                <li>
                            <a class="dropdown-item" href="{% url 'users:logout' %}">
                                Выйти
                            </a>
                        </li>
                    </ul>
                    </li>
                      {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:login' %}">Войти <i class="fas fa-sign-in-alt"></i></a></li>
                </li>
{% endif %}
            </ul>
        </div>
    </div>
</nav>

<!-- Page Content -->
<section class="custom-section">
    <h1 class="mt-5">Салон проката</h1>
    <ul>
        <li><a class="nav-link" style="color: black;padding: 0" href="{% url 'products:index' %}">Выбрать авто</a></li>
        <li><a class="nav-link" style="color: black;padding: 0" href="{% url 'products:about' %}">Условия </a></li>
     </ul>
{#    <div class="container">#}
{#        <div class="row">#}
{#                    <div class="col-12 d-flex justify-content-between">#}
{#                        <h1 class="mt-5">Салон проката</h1>#}
{#                        <h2 class="text-right mt-5">Наши контакты:</h2>#}
{#       </div>#}
{#                <p> <pre>#}
{##}
{#  Салон предоставляет авто в аренду для любых целей и на любые сроки.                                                     <span style="font-size: 130%;font-weight:bold;text-decoration: underline;">+375291685241</span>#}
{#  Бесплатная доставка по всему городу! У нас вы найдете самые выгодные условия аренды.                                    <span style="font-size: 130%;font-weight:bold;text-decoration: underline;">+375445566999</span>#}
{#                </pre>#}
{#                 </p>#}
{#                <button id="start-purchase-btn" type="button" class="btn btn-lg">#}
{#                    <a id="start-purchase-link" href="{% url 'products:index' %}">#}
{#                        Выбрать автомобиль#}
{#                    </a>#}
{#                </button>#}
{#            </div>#}
{#        </div>#}
{#    </div>#}
</section>


<!-- Bootstrap core JavaScript -->

<script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>

<!-- FontAwesome script -->
{#<script src="{% static 'vendor/fontawesome/fontawesome-icons.js' %}" crossorigin="anonymous"></script>#}

</body>

</html>

store/products/templates/products/products.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Салон проката</title>


    <link rel="shortcut icon" type="image/png" href="{% static "vendor/icon/darkicon.png" %}">
    <!-- Bootstrap core CSS -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link rel="stylesheet" href="{% static 'vendor/css/products.css' %}" id="theme">
    <link href="{% static 'vendor/css/toggle.css' %}" rel="stylesheet">

</head>

<body>

<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top my-navbar">
    <div class="container">
        <a class="navbar-brand" href="{% url 'index' %}">Салон проката</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <li class="nav-link"><label class="toggle-switch" style="margin-top: 5px">
                    <input type="checkbox">
                    <span class="toggle-switch-label">
                      <span id="switchMode" class="toggle-switch-handle"></span>
                    </span>
                </label></li>
                {#                <li class="nav-link"><button id= "switchMode">Switch</button></li>#}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'products:about' %}">Условия аренды <i
                            class="fas fa-shopping-bag"></i> </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'products:index' %}">Каталог <i class="fas fa-shopping-bag"></i>
                    </a>
                </li>
                {% if user.is_authenticated %}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                           data-bs-toggle="dropdown" aria-expanded="false">
                            <i class="fas fa-user-circle"></i>
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li>
                                <a class="dropdown-item" href="{% url 'users:profile' %}">Профиль</a>
                            </li>
                            {% if user.is_superuser or user.is_staff %}
                                <li><a class="dropdown-item" href="{% url 'admin:index' %}">Админ-панель</a></li>
                            {% endif %}
                            <li>
                                <hr class="dropdown-divider">
                            </li>
                            <li>
                                <a class="dropdown-item" href="{% url 'users:logout' %}">
                                    Выйти
                                </a>
                            </li>
                        </ul>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:login' %}">Войти <i class="fas fa-sign-in-alt"></i></a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

<!-- Page Content -->
<div class="container">


    <div class="row">


        <div class="col-lg-3">

            <h1 class="my-4">Прокат</h1>
            <div class="list-group">
                {% for category in categories %}
                    <a href="{% url 'products:category' category.id %}" class="list-group-item">{{ category.name }}</a>
                {% endfor %}

            </div>

        <div class=" filter-group">
        <h5>Дополнительные параметры</h5>
                {% for filter in filters %}
                    <a href="{% url 'products:filter' filter.id %}" class="list-group-item">{{ filter.name }}</a>
                {% endfor %}
            </div>
        </div>

        <!-- /.col-lg-3 -->

        <div class="col-lg-9">

            <div id="carouselExampleIndicators" class="carousel slide my-4" data-ride="carousel">
                <ol class="carousel-indicators">
                    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
                </ol>
                <div class="carousel-inner" role="listbox">
                    <div class="carousel-item active">
                        <img class="d-block img-fluid" src="/static/vendor/img/slides/slide.jpg" alt="First slide">
                    </div>
                    <div class="carousel-item">
                        <img class="d-block img-fluid" src="/static/vendor/img/slides/remazda2.jpg" alt="Second slide">
                    </div>
{#                    <div class="carousel-item">#}
{#                        <img class="d-block img-fluid" src="/static/vendor/img/slides/refolk.jpg" alt="Third slide">#}
{#                    </div>#}
                </div>
                <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </a>
            </div>



            <div class="row">

                {% for product in products %}
                    <div class="col-lg-4 col-md-6 mb-4">
                        <div class="card h-100">
                            <a href="#">
                                <img class="card-img-top"
                                     src="{{ product.image.url }}"
                                     alt="">
                            </a>
                            <div class="card-body">
                                <h4 class="card-title">
                                    <a href="#">{{ product.name }}</a>
                                </h4>
                                <h5>{{ product.price }} руб. в день</h5>
                                <p class="card-text">{{ product.description }}</p>
                            </div>
                            <div class="card-footer text-center">
{#                                <a class="btn-outline-success" href="{% url 'products:basket_add' product.id %}">Арендовать</a>#}
                                <a class="btn-outline-success" href="{% url 'products:product_page' product.id  %}">Арендовать</a>
{#                                   onclick="redirectToAnotherPage('{% url 'orders:order-create' %}')">#}
{#                                <script>#}
{#                                    function redirectToAnotherPage(url) {#}
{#                                        window.location.href = url;#}
{#                                    }#}
{#                                </script>#}


                                {#                             <a class ="btn-outline-success"#}
                                {#                               href="{% url 'orders:order_create' %}">Арендовать</a>#}
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>


{#            <nav aria-label="Page navigation example">#}
{#                <ul class="pagination justify-content-center">#}
{#                    <li class="page-item disabled">#}
{#                        <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Previous</a>#}
{#                    </li>#}
{#                    <li class="page-item"><a class="page-link" href="#">1</a></li>#}
{#                    <li class="page-item"><a class="page-link" href="#">2</a></li>#}
{#                    <li class="page-item"><a class="page-link" href="#">3</a></li>#}
{#                    <li class="page-item">#}
{#                        <a class="page-link" href="#">Next</a>#}
{#                    </li>#}
{#                </ul>#}
{#            </nav>#}

            <nav aria-label="Page navigation example">
                        <ul class="pagination justify-content-center">
                            <li class="page-item {% if not products.has_previous %} disabled {% endif %}">
                                <a class="page-link"
                                   href="{% if products.has_previous %} {% url 'products:paginator' products.previous_page_number %} {% else %} # {% endif %}"
                                   tabindex="-1" aria-disabled="true">
                                    Предыдущая
                                </a>
                            </li>
                            {% for page in products.paginator.page_range %}
                                <li class="page-item">
                                    <a class="page-link" href="{% url 'products:paginator' page %}">
                                        {{ page }}
                                    </a>
                                </li>
                            {% endfor %}
                            <li class="page-item {% if not products.has_next %} disabled {% endif %}">
                                <a class="page-link"
                                   href="{% if products.has_next %} {% url 'products:paginator' products.next_page_number %} {% else %} # {% endif %}">
                                    Следующая
                                </a>
                            </li>
                        </ul>
                    </nav>

        </div>

    </div>

</div>
<!-- /.container -->

<!-- Footer -->
{#<footer class="py-5 bg-dark">#}
{#    <div class="container">#}
{#        <p class="m-0 text-center text-white">2023</p>#}
{#    </div>#}
{#    <!-- /.container -->#}
{#</footer>#}

<footer class="py-5 bg-dark my-footer">
    <div class="container">
        <div class="row">
            <div class="col-lg-4 text-left">
                <p class="m-0 text-white">ООО "Аренда транспорта"</p>
            </div>
            <div class="col-lg-4 text-center">
                <p class="m-0 text-white">© 2023 Аренда и прокат транспорта по всей Беларуси - "Salon Group"</p>
            </div>
            <div class="col-lg-4 text-right">
                <p class="m-0 text-white">Наш контактный номер:</p>
                <p class="m-0 text-white font-weight-bold underline">+37544738377</p>
            </div>
        </div>
    </div>
    <!-- /.container -->
</footer>



<script>
    function toggleColor() {
        // Получаем элемент переключателя
        var toggleSwitch = document.querySelector('.toggle-switch');

        // Инвертируем состояние переключателя
        toggleSwitch.classList.toggle('toggle-switch-dark');
    }
</script>





<script>
    document.addEventListener('DOMContentLoaded', function () {
        // Получаем элементы
        let switchMode = document.getElementById("switchMode");
        let theme = document.getElementById("theme");

        // Проверка сохраненной темы в локальном хранилище
        const savedTheme = localStorage.getItem('theme');
        if (savedTheme) {
            theme.href = savedTheme;
        }

        // Обработчик события для переключения темы
        switchMode.onclick = function () {
            // Переключение между темами
            if (theme.getAttribute("href") === "{% static 'vendor/css/products.css' %}") {
                theme.href = "{% static 'vendor/css/dark-mode.css' %}";
            } else {
                theme.href = "{% static 'vendor/css/products.css' %}";
            }

            // Сохранение выбранной темы в локальном хранилище
            localStorage.setItem('theme', theme.href);
        };
    });
</script>

<!-- Bootstrap core JavaScript -->
{#<script src = "{% static 'vendor/js/dark.js' %}"></script>#}
<script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>


<!-- FontAwesome script -->
<script src="{% static 'vendor/fontawesome/fontawesome-icons.js' %}" crossorigin="anonymous"></script>

</body>

</html>