store/store/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from products.views import index
# from store.admin import admin_site
from django.contrib import admin

admin.site.site_header = 'Панель администрации'  # default: "Django Administration"
admin.site.index_title = 'Админ панель'
admin.site.site_title = 'Пользователь'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('products/', include('products.urls', namespace='products')),
    path('users/', include('users.urls', namespace='users')),
    path('account/', include("django.contrib.auth.urls")),
    path('orders/', include('orders.urls', namespace='orders')),
    path('accounts/', include('allauth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/users/urls.py
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from users.views import login, registration, logout, WebPasswordResetView, profile
from orders.views import OrderListView

app_name = 'users'

urlpatterns = [
  path('login/', login, name='login'),
  path('registration/', registration, name='registration'),
  path('profile/', profile, name='profile'),
  path('logout/', logout, name='logout'),
  path("password_reset/", WebPasswordResetView.as_view(), name="password_reset"),
  # path("password_reset/success/", WebPasswordResetDone.as_view(), name="password_reset_success"),
  path('profile/', OrderListView.as_view(), name="orders_list"),

]

store/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    image = models.ImageField(upload_to='users_images', null=True, blank=True)
    age = models.PositiveIntegerField(null=True, blank=True)

store/users/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm

from users.models import User


class UserLoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control py-4', 'placeholder': 'Введите имя пользователя'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control py-4', 'placeholder': 'Введите пароль'}))

    class Meta:
        model = User
        fields = ('username', 'password')


class UserRegistrationForm(UserCreationForm):
    first_name = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control py-4', 'placeholder': 'Введите имя'}))
    last_name = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control py-4', 'placeholder': 'Введите фамилию'}))
    username = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control py-4', 'placeholder': 'Введите имя пользователя'}))
    age = forms.IntegerField(widget=forms.NumberInput(attrs={
        'class': 'form-control py-4', 'placeholder': 'Введите возраст',
        'min': 16,  # Минимальный возраст
        'max': 150,  # Максимальный возраст (примерное значение)
    }))
    email = forms.EmailField(widget=forms.EmailInput(attrs={
        'class': 'form-control py-4', 'placeholder': 'Введите адрес электронной почты'}))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control py-4', 'placeholder': 'Введите пароль'}))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control py-4', 'placeholder': 'Подтвердите пароль'}))

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username', 'age', 'email', 'password1', 'password2')
        # fields = UserCreationForm.Meta.fields + ("email",)


class UserProfileForm(UserChangeForm):
    first_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control py-4', 'readonly': True}))
    last_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control py-4', 'readonly': True}))

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'image')


class PasswordEmailForm(forms.Form):
    email = forms.EmailField(widget=forms.EmailInput(attrs={
        'class': 'emailInput', 'placeholder': "example@example.com"}))
    class Meta:
        fields = ('email',)

store/users/views.py
from django.contrib.auth.views import PasswordResetView, PasswordResetDoneView
from django.shortcuts import render, HttpResponseRedirect
from django.contrib import auth, messages
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from users.models import User
from users.forms import UserLoginForm, UserRegistrationForm, UserProfileForm, PasswordEmailForm
from products.models import Basket


def login(request):
    if request.method == 'POST':
        form = UserLoginForm(data=request.POST)
        if form.is_valid():
            username = request.POST['username']
            password = request.POST['password']
            user = auth.authenticate(username=username, password=password)
            if user:
                auth.login(request, user)
                return HttpResponseRedirect(reverse('index'))
    else:
        form = UserLoginForm()
    context = {'form': form}
    return render(request, 'users/login.html', context)


def registration(request):
    if request.method == 'POST':
        form = UserRegistrationForm(data=request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Регистрация прошла успешно!')
            return HttpResponseRedirect(reverse('users:login'))
    else:
        form = UserRegistrationForm()
    context = {'form': form}
    return render(request, 'users/registration.html', context)


def logout(request):
    auth.logout(request)
    return HttpResponseRedirect(reverse('index'))


@login_required
def profile(request):
    form = UserProfileForm(instance=request.user)
    context = {'title': 'Салон проката', 'form': form}
    return render(request, 'users/profile.html', context)


class WebPasswordResetView(PasswordResetView):
    template_name = 'users/password_reset_email.html'


# class WebPasswordResetDone(PasswordResetDoneView):
#     template_name = 'users/password_reset_success.html'

store/users/templates/users/login.html
{% load static %}

{% load socialaccount %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <meta name="description" content=""/>
    <meta name="author" content=""/>
    <title>Прокат - Авторизация</title>

    <link rel="shortcut icon" type="image/png" href="{% static "vendor/icon/darkicon.png" %}">

    <link href="{% static 'vendor/css/auth.css' %}" rel="stylesheet"/>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/js/all.min.js"
            crossorigin="anonymous"></script>
</head>
<body class="bg-primary">
<div id="layoutAuthentication">
    <div id="layoutAuthentication_content">
        <main>
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-lg-5">
                        {% if messages or form.non_field_errors %}
                            <div class="alert
                             {% if messages  %}alert-success {% else %} alert-warning {% endif %}
                             alert-dismissible fade show" role="alert"
                             style="margin-top: 50px;">
                                 {% if messages %}
                                     {% for message in messages %}
                                     {{ message }}
                                     {% endfor %}
                                 {% else %}
                           {{ form.non_field_errors }}
                                 {% endif %}
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        {% endif %}
                        <div class="card shadow-lg border-0 rounded-lg mt-5">
                            <div class="card-header"><h3 class="text-center font-weight-light my-4">Авторизация</h3>
                            </div>
                            <div class="card-body">
                                <form action = "{% url 'users:login' %}" method="post">
                                    {% csrf_token %}
                                    <div class="form-group">
                                        <label class="small mb-1" for="{{ form.username.id_for_label }}">Имя пользователя</label>
                                        {{ form.username }}
                                    </div>
                                    <div class="form-group">
                                        <label class="small mb-1" for="{{ form.password.id_for_label }}">Пароль</label>
                                        {{ form.password }}
                                    </div>
                                    <div class="form-group d-flex align-items-center justify-content-between mt-4 mb-0">
                                        <a class="small" href="{% url 'users:password_reset' %}">Забыли пароль?</a>
                                        <input class="btn btn-primary" type="submit" value="Авторизоваться">
                                    </div>
                                    <div class="form-group d-flex align-items-center justify-content-center mt-4 ">
                                        <a href="#">
                                            <i class="fab fa-google fa-2x" style="color: #d9503e;margin-right:50px "></i>
                                        </a>
                                        <a href="{% provider_login_url 'github' %}">
                                            <i class="fab fa-github fa-2x" style="color: #303030;"></i>
                                        </a>
                                    </div>
                                </form>
                            </div>
                            <div class="card-footer text-center">
                                <div class="small"><a href="{% url 'users:registration' %}">Нужен аккаунт? Зарегистрируйся!</a></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </main>
    </div>
</div>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
        crossorigin="anonymous"></script>
<script src="{% static 'vendor/js/auth-admin.js' %}"></script>
</body>
</html>

store/users/templates/users/password_reset_email.html
{#<!DOCTYPE html>#}
{#<html lang="en">#}
{#<head>#}
{#    <meta charset="UTF-8">#}
{#    <title>Password reset</title>#}
{#</head>#}
{#<body>#}
{#<form method="post">#}
{#{% csrf_token %}#}
{#{{ form }}#}
{#<button type="submit">SUBMIT</button>#}
{#</form>#}
{#</body>#}
{#</html>#}

{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <link href="{% static 'vendor/css/reset.css' %}" rel="stylesheet">
    <link rel="shortcut icon" type="image/png" href="{% static "vendor/icon/darkicon.png" %}">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <style>


        .emailInput {
            padding: 10px;
            margin: 10px 0;
            width: 300px;
            box-sizing: border-box;
        }

        .form-container {
            text-align: center;
        }

        h2 {
            color: #333;
        }

        #emailInput {
            padding: 10px;
            margin: 10px 0;
            width: 300px;
            box-sizing: border-box;
        }

        #submitButton {
            padding: 10px;
            background-color: rgb(39, 41, 135);
            color: white;
            border: none;
            cursor: pointer;
        }

        #submitButton:hover {
            background-color: #1d135c;
        }
    </style>
    <title>Email Form</title>
</head>
<body>

<div class="form-container">
    <h2>Введите ваш email</h2>
    <form method="post">
        {% csrf_token %}
        <label for="{{ form.email.id_for_label }}"></label>
        {{ form.email }}

        {#      <br>#}
        <button type="submit" id="submitButton">Отправить</button>
    </form>
</div>

</body>
</html>

store/users/templates/users/password_reset_success.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <meta name="description" content=""/>
    <meta name="author" content=""/>
    <title>Салон - Спасибо за заказ!</title>
    <link href="{% static 'vendor/css/auth.css' %}" rel="stylesheet"/>
</head>
<body class="bg-primary">
<div id="layoutAuthentication">
    <div id="layoutAuthentication_content">
        <main>
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-lg-5">
                        <div class="card shadow-lg border-0 rounded-lg mt-5">
                            <div class="card-header">
                                <h3 class="text-center font-weight-light my-4">Спасибо за обращение!</h3>
                            </div>
                            <div class="card-body text-center" style="padding: 40px;margin-bottom: 10px;">
                                <h4>
                                    На указанный имейл отправлена ссылка для восстановленя пароля.
                                </h4>
                                <button type="button" class="btn btn-primary">
                                    <a class="nav-link" style="color: white" href="{% url 'products:index' %}">Вернуться на главную </a>
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </main>
    </div>
</div>
</body>
</html>

store/users/templates/users/profile.html
{% extends 'products/base.html' %}
{% load static %}




{% block css %}
    <link href="{% static 'vendor/css/profile.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
<div class="container">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-6 text-center">
                <h2 class="mt-3 mb-3">Профиль</h2>
                <div class="row">
                    <div class="col-lg-6">
                        <!-- Ваш текст или контент -->
                        <img width="150" height="150" src="{% if user.image %} {% else %} {% static 'vendor/img/avatar.jpg' %} {% endif %}"
                             class="img-thumbnail float-right rounded-circle mt-3">

                    </div>
                    <div class="col-lg-6">
                        <form action="{% url 'users:profile' %}" method="post">
                            {% csrf_token %}
                            <div class="form-row ">
                                <div class="col-lg-12">
                                    <div class="form-group">
                                        <label class="small mb-1" for="{{ form.first_name.id_for_label }}">Имя</label>
                                        {{ form.first_name }}
                                    </div>
                                </div>
                                </div>
                                <div class="form-row">
                                   <div class="col-lg-12">
                                    <div class="form-group">
                                        <label class="small mb-1" for="{{ form.last_name.id_for_label }}">Фамилия</label>
                                        {{ form.last_name }}
                                    </div>
                                 </div>
                               </div>
                        </form>

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
    <section>
    <div class="container pt-6">
        <div class="text-center mt-6">
            <h3>Заказы</h3>
            <div class="orders mt-6">
                <table class="table">
                    <thead>
                    <tr class="table-light">
                        <th scope="col">#</th>
                        <th scope="col">Статус</th>
                        <th scope="col">Создан</th>
                        <th scope="col">Итого</th>
                        <th scope="col">Действие</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for order in object_list %}

                    <tr class="table-success">
                        <th scope="row">{{ order.id }}</th>
                        <td>{{ order.status }}</td>
                        <td>{{ order.created }}</td>
                        <td>{{ order.price }} руб.</td>
                        <td>
                            <a href="order.html">просмотреть</a>
                        </td>
                    </tr>
                    {% endfor %}
                                        <tr>
                        <th scope="row">1</th>
                        <td>Оплачен</td>
                        <td>8 дек. 23 года</td>
                        <td>5 070 руб.</td>
                        <td>
                            <a href="order.html">просмотреть</a>
                        </td>
                    </tr>

{#                    <tr class="table-info">#}
{#                        <th scope="row">3</th>#}
{#                        <td>В пути</td>#}
{#                        <td>14 нояб. 21 года</td>#}
{#                        <td>9 566 руб.</td>#}
{#                        <td>#}
{#                            <a href="order.html">просмотреть</a>#}
{#                        </td>#}
{#                    </tr>#}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</section>

{% endblock %}

store/users/templates/users/registration.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <meta name="description" content=""/>
    <meta name="author" content=""/>
    <title>Прокат - Регистрация</title>
    <link href="{% static 'vendor/css/auth.css' %}" rel="stylesheet"/>
    <link rel="shortcut icon" type="image/png" href="{% static "vendor/icon/darkicon.png" %}">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/js/all.min.js"
            crossorigin="anonymous"></script>
</head>
<body class="bg-primary">
<div id="layoutAuthentication">
    <div id="layoutAuthentication_content">
        <main>
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-lg-7">
                        {% if form.errors %}
                            <div class="alert alert-warning alert-dismissible fade show" role="alert"
                             style="margin-top: 50px;">
                           {{ form.errors }}
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        {% endif %}
                        <div class="card shadow-lg border-0 rounded-lg mt-5">
                            <div class="card-header"><h3 class="text-center font-weight-light my-4">Создать аккаунт</h3>
                            </div>
                            <div class="card-body">
                                <form action="{% url 'users:registration' %}" method="post">
                                      {% csrf_token %}
                                    <div class="form-row">
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label class="small mb-1" for="{{ form.first_name.id_for_label }}">Имя</label>
                                                {{ form.first_name }}
                                            </div>
                                        </div>
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label class="small mb-1" for="{{ form.last_name.id_for_label }}">Фамилия</label>
                                                {{ form.last_name }}
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-row">
                                        <div class="col-md-6">
                                            <label class="small mb-1" for="{{ form.username.id_for_label }}">Имя пользователя</label>
                                            {{ form.username }}
                                        </div>

                                           <div class="col-md-6">
                                              <label class="small mb-1" for="{{ form.age.id_for_label }}">Возраст</label>
                                              {{ form.age }}
                                           </div>

                                    </div>
                                    <div class="form-row">
                                    <div class="col-md-12">
                                            <label class="small mb-1" for="{{ form.email.id_for_label }}">Адрес электронной
                                                почты</label>
                                                {{ form.email }}
                                        </div>
                                    </div>
                                    <div class="form-row">
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label class="small mb-1" for="{{ form.password1.id_for_label }}">Пароль</label>
                                                {{ form.password1 }}
                                            </div>
                                        </div>
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label class="small mb-1" for="{{ form.password1.id_for_label }}">Подтверждение
                                                    пароля</label>
                                               {{ form.password2 }}
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-group mt-4 mb-0">
                                        <input class="btn btn-primary btn-block" type="submit" value="Создать аккаунт">
                                    </div>
                                </form>
                            </div>
                            <div class="card-footer text-center">
                                <div class="small"><a href="login.html">Уже есть аккаунт? Авторизоваться</a></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </main>
    </div>
</div>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
        crossorigin="anonymous"></script>
<script src="{% static 'vendor/js/auth-admin.js' %}"></script>
</body>
</html>