store/orders/urls.py
from django.urls import path, include

from orders.views import OrderCreateView, Success

app_name = 'orders'

urlpatterns = [
   path('order-create/', OrderCreateView.as_view(), name='order-create'),
   path('success/', Success.as_view(), name='success'),
   # path('order-create/', order, name='order-create')
]

store/store/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from products.views import index
# from store.admin import admin_site
from django.contrib import admin

admin.site.site_header = 'Панель администрации'  # default: "Django Administration"
admin.site.index_title = 'Админ панель'
admin.site.site_title = 'Пользователь'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('products/', include('products.urls', namespace='products')),
    path('users/', include('users.urls', namespace='users')),
    path('account/', include("django.contrib.auth.urls")),
    path('orders/', include('orders.urls', namespace='orders')),
    path('accounts/', include('allauth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/orders/models.py
from django.db import models

from products.models import Basket
from users.models import User


class Order(models.Model):
    CREATED = 0
    PAID = 1
    ON_WAY = 2
    DELIVERED = 3
    STATUSES = (
        (CREATED, 'Создан'),
        (PAID, 'Оплачен'),
        (ON_WAY, 'В пути'),
        (DELIVERED, 'Доставлен'),
    )

    first_name = models.CharField(max_length=64)
    last_name = models.CharField(max_length=64)
    email = models.EmailField(max_length=256)
    address = models.CharField(max_length=256)
    basket_history = models.JSONField(default=dict)
    created = models.DateTimeField(auto_now_add=True)
    status = models.SmallIntegerField(default=CREATED, choices=STATUSES)
    initiator = models.ForeignKey(to=User, on_delete=models.CASCADE)

    def __str__(self):
        return f'Order #{self.id}. {self.first_name} {self.last_name}'

store/orders/forms.py
from django import forms

from orders.models import Order


class OrderForm(forms.ModelForm):
    first_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Иван'}))
    last_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Иванов'}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'you@example.com'}))
    address = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control', 'placeholder': 'Беларусь, Минск, ул. Гикало, дом 7',
    }))

    class Meta:
        model = Order
        fields = ('first_name', 'last_name', 'email', 'address')

store/orders/views.py
from django.shortcuts import render
from django.urls import reverse, reverse_lazy
from django.views.generic.base import TemplateView
from django.views.generic.edit import CreateView
from orders.forms import OrderForm
from products.models import Basket
from orders.models import Order
from django.views.generic.list import ListView
from django.contrib import messages
from django.shortcuts import render, HttpResponseRedirect


class OrderCreateView(CreateView):
    template_name = 'orders/order-create.html'
    form_class = OrderForm
    success_url = reverse_lazy('orders:success')


    def form_valid(self, form):
        form.instance.initiator = self.request.user
        return super(OrderCreateView, self).form_valid(form)

    def get_context_data(self, **kwargs):
        context = super(OrderCreateView, self).get_context_data()
        context['baskets'] = Basket.objects.filter(user=self.request.user)
        return context


class OrderListView(ListView):
    template_name = 'users/profile.html'
    queryset = Order.objects.all()
    ordering = ('-created')

    def get_queryset(self):
        queryset = super(OrderListView, self).get_queryset()
        return queryset.filter(initiator=self.request.user)


class Success(TemplateView):
    template_name = 'orders/success.html'

# def order(request):
#     if request.method == 'POST':
#         form = OrderForm(data=request.POST)
#         if form.is_valid():
#             form.save()
#             return HttpResponseRedirect(reverse('products:index'))
#     else:
#         form = OrderForm()
#     context = {'form': form}
#     return render(request, 'orders/order-create.html', context)

store/orders/templates/orders/order-create.html
{#{% load static %}#}
{##}
{#<!DOCTYPE html>#}
{#<html lang="en">#}
{##}
{#<head>#}
{##}
{#    <meta charset="utf-8">#}
{#    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">#}
{#    <meta name="description" content="">#}
{#    <meta name="author" content="">#}
{##}
{#    <title>Store - Оформление заказа</title>#}
{##}
{#    <!-- Bootstrap core CSS -->#}
{#    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">#}
{##}
{#    <!-- Custom styles for this template -->#}
{#    <link href="{% static 'vendor/css/orders.css' %}" rel="stylesheet">#}
{##}
{#</head>#}
{##}
{#<body>#}
{##}
{#<!-- Navigation -->#}
{#<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">#}
{#    <div class="container">#}
{#        <a class="navbar-brand" href="../index.html">Store</a>#}
{#        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"#}
{#                aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">#}
{#            <span class="navbar-toggler-icon"></span>#}
{#        </button>#}
{#        <div class="collapse navbar-collapse" id="navbarResponsive">#}
{#            <ul class="navbar-nav ml-auto">#}
{#                <li class="nav-item">#}
{#                    <a class="nav-link" href="../products.html">Каталог <i class="fas fa-shopping-bag"></i> </a>#}
{#                </li>#}
{#                <li class="nav-item">#}
{#                    <a class="nav-link" href="../users/login.html">Войти <i class="fas fa-sign-in-alt"></i></a>#}
{#                </li>#}
{#                <li class="nav-item dropdown">#}
{#                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"#}
{#                       data-bs-toggle="dropdown" aria-expanded="false">#}
{#                        <i class="fas fa-user-circle"></i>#}
{#                    </a>#}
{#                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">#}
{#                        <li>#}
{#                            <a class="dropdown-item" href="../users/profile.html">Профиль</a>#}
{#                        </li>#}
{#                        <li><a class="dropdown-item" href="../orders/orders.html">Заказы</a></li>#}
{#                        <li><a class="dropdown-item" href="#">Админ-панель</a></li>#}
{#                        <li>#}
{#                            <hr class="dropdown-divider">#}
{#                        </li>#}
{#                        <li>#}
{#                            <a class="dropdown-item" href="#">#}
{#                                Выйти#}
{#                            </a>#}
{#                        </li>#}
{#                    </ul>#}
{#                </li>#}
{#            </ul>#}
{#        </div>#}
{#    </div>#}
{#</nav>#}
{##}
{#<!-- Page Content -->#}
{#<section>#}
{#    <div class="alert alert-warning text-center" role="alert">#}
{#        Пожалуйста, заполните адрес электронной почты.#}
{#    </div>#}
{#    <div class="container">#}
{#        <div class="py-5 text-center">#}
{#            <h1>Оформление заказа</h1>#}
{#        </div>#}
{#        <div class="row g-5">#}
{#            <div class="col-md-5 col-lg-4 order-md-last">#}
{#                <h4 class="d-flex justify-content-between align-items-center mb-3">#}
{#                    <span class="text-primary">Заказ</span>#}
{#                    <span class="badge badge-primary badge-pill text-white">3</span>#}
{#                </h4>#}
{#                <ul class="list-group mb-3">#}
{#                    <li class="list-group-item d-flex justify-content-between lh-sm">#}
{#                        <div>#}
{#                            <h6 class="my-0">Product name</h6>#}
{#                            <small class="text-muted">2 шт.</small>#}
{#                        </div>#}
{#                        <span class="text-muted">11 400 руб.</span>#}
{#                    </li>#}
{#                    <li class="list-group-item d-flex justify-content-between lh-sm">#}
{#                        <div>#}
{#                            <h6 class="my-0">Second product</h6>#}
{#                            <small class="text-muted">1 шт.</small>#}
{#                        </div>#}
{#                        <span class="text-muted">3 200 руб.</span>#}
{#                    </li>#}
{#                    <li class="list-group-item d-flex justify-content-between lh-sm">#}
{#                        <div>#}
{#                            <h6 class="my-0">Third item</h6>#}
{#                            <small class="text-muted">3 шт.</small>#}
{#                        </div>#}
{#                        <span class="text-muted">12 894 руб.</span>#}
{#                    </li>#}
{#                    <li class="list-group-item d-flex justify-content-between">#}
{#                        <span>Сумма к оплате</span>#}
{#                        <strong>27 497 руб.</strong>#}
{#                    </li>#}
{#                </ul>#}
{#            </div>#}
{#            <div class="col-md-7 col-lg-8">#}
{#                <h4 class="mb-3">Данные для заполнения</h4>#}
{#                <form action="{% url 'orders:order-create' %}" method="post">#}
{#                    {%  csrf_token %}#}
{#                    <div class="row g-3">#}
{#                       <div class="col-sm-6">#}
{#    <label for="{{ form.first_name.id_for_label }}" class="form-label">Имя</label>#}
{#    {{ form.first_name }}#}
{#    <input type="text" id="{{ form.first_name.id_for_label }}" name="{{ form.first_name.html_name }}" autocomplete="given-name">#}
{#</div>#}
{##}
{#                        <div class="col-sm-6">#}
{#                            <label for="{{ form.last_name.id_for_label }}" class="form-label">Фамилия</label>#}
{#                             {{ form.last_name }}#}
{#                        </div>#}
{#                        <div class="col-12 mt-3">#}
{#                            <label for="email" class="form-label">Адрес электронной почты</label>#}
{#                            <input type="email" class="form-control" id="email" placeholder="you@example.com">#}
{#                        </div>#}
{##}
{#                        <div class="col-12 mt-3">#}
{#                            <label for="address" class="form-label">Адрес</label>#}
{#                            <input type="text" class="form-control" id="address" placeholder="Россия, Москва, ул. Мира, дом 6" >#}
{#                        </div>#}
{##}
{#                    </div>#}
{##}
{##}
{#                    <hr class="my-4">#}
{##}
{#                    <button class="w-100 btn btn-primary btn-lg" type="submit">Продолжить</button>#}
{#                </form>#}
{#            </div>#}
{#        </div>#}
{#    </div>#}
{#</section>#}
{##}
{#<!-- Bootstrap core JavaScript -->#}
{#<script src="{% static '/vendor/jquery/jquery.min.js' %}"></script>#}
{#<script src="{% static '/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>#}
{#<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"#}
{#        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"#}
{#        crossorigin="anonymous"></script>#}
{##}
{#<!-- FontAwesome script -->#}
{#<script src="#" crossorigin="anonymous"></script>#}
{##}
{#</body>#}
{##}
{#</html>#}



{% extends 'products/base.html' %}

{% block content %}
    <section>
{#        <div class="alert alert-warning text-center" role="alert">#}
{#            Пожалуйста, заполните адрес электронной почты.#}
{#        </div>#}
        <div class="container">
            <div class="py-5 text-center">
                <h1>Оформление заказа</h1>
            </div>
            <div class="row g-5">
                <div class="col-md-5 col-lg-4 order-md-last">
                    <h4 class="d-flex justify-content-between align-items-center mb-3">
                        <span class="text-primary">Заказ</span>
                        <span class="badge badge-primary badge-pill text-white">{{ baskets.total_quantity }}</span>
                    </h4>
                    <ul class="list-group mb-3">
                        {% for basket in baskets %}
                            <li class="list-group-item d-flex justify-content-between lh-sm">
                                <div>
                                    <h6 class="my-0">{{ basket.product.name }}</h6>
                                    <small class="text-muted">{{ basket.quantity }} дней аренды.</small>
                                </div>
                                <span class="text-muted">{{ basket.sum }} руб.</span>
                            </li>
                        {% endfor %}
                        <li class="list-group-item d-flex justify-content-between">
                            <span>Сумма к оплате</span>
                            <strong>{{ baskets.total_sum}} руб.</strong>
                        </li>
                    </ul>
                </div>
                <div class="col-md-7 col-lg-8">
                    <h4 class="mb-3">Введите данные</h4>
                    <form action="{% url 'orders:order-create' %}" method="post">
                        {% csrf_token %}
                        <div >{{ form.non_field_errors }}</div>
                        <div class="row g-3">
                            <div class="col-sm-6">
                                <label for = "{{ form.first_name.id_for_label }}" class="form-label">Имя</label>
                                {{ form.first_name }}
                            </div>
                            <div class = "row-form-errors">{{ form.first_name.errors }}</div>

                            <div class="col-sm-6">
                                <label for="{{ form.last_name.id_for_label }}" class="form-label">Фамилия</label>
                                {{ form.last_name }}
                            </div>

                            <div class="col-12 mt-3">
                                <label for="{{ form.email.id_for_label }}" class="form-label">Адрес электронной
                                    почты</label>
                                {{ form.email }}
                            </div>

                            <div class="col-12 mt-3">
                                <label for="{{ form.email.address }}" class="form-label">Адрес</label>
                                {{ form.address }}
                            </div>

                        </div>

                        <hr class="my-4">

                        <button class="w-100 btn btn-primary btn-lg" type="submit">Продолжить</button>
                    </form>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

store/orders/templates/orders/success.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <meta name="description" content=""/>
    <meta name="author" content=""/>
    <title>Салон - Спасибо за заказ!</title>
    <link href="{% static 'vendor/css/auth.css' %}" rel="stylesheet"/>
</head>
<body class="bg-primary">
<div id="layoutAuthentication">
    <div id="layoutAuthentication_content">
        <main>
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-lg-5">
                        <div class="card shadow-lg border-0 rounded-lg mt-5">
                            <div class="card-header">
                                <h3 class="text-center font-weight-light my-4">Спасибо за заказ!</h3>
                            </div>
                            <div class="card-body text-center" style="padding: 40px;margin-bottom: 10px;">
                                <h4>
                                    Ваш заказ успешно сформирован.
                                </h4>
                                <button type="button" class="btn btn-primary">
                                    <a class="nav-link" style="color: white" href="{% url 'products:index' %}">Вернуться на главную </a>
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </main>
    </div>
</div>
</body>
</html>